name: latery
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-146.2.beta <3.0.0"

dependencies:
  any_link_preview: ^3.0.0
  cloud_firestore: ^4.3.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  file_picker: ^5.2.4
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.9
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  fpdart: ^0.4.0
  google_sign_in: ^5.4.2
  routemaster: ^1.0.1
  shared_preferences: ^2.0.15
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/awards/

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
