// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKo2gJdzc_56yaGDUsr7FUUlwQXdzuj10',
    appId: '1:723003670550:web:35dfa043295aa2b6473537',
    messagingSenderId: '723003670550',
    projectId: 'latery-core',
    authDomain: 'latery-core.firebaseapp.com',
    storageBucket: 'latery-core.appspot.com',
    measurementId: 'G-9SQMR1LB93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9W4hYCCICmyTsPYUh6Cgwie5eQJ0UV6U',
    appId: '1:723003670550:android:ef499cb1d4631313473537',
    messagingSenderId: '723003670550',
    projectId: 'latery-core',
    storageBucket: 'latery-core.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_8Ko6dKK7Pr3OQL0OghLr7MzLLAbY3cg',
    appId: '1:723003670550:ios:67cc5c5285c95353473537',
    messagingSenderId: '723003670550',
    projectId: 'latery-core',
    storageBucket: 'latery-core.appspot.com',
    iosClientId: '723003670550-rsbu69deqged6im3c0c3g5g3iapsgl4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.latery',
  );
}
